AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFront Distribution con ACM + Behaviors + Route 53

Parameters:
  DomainName:
    Type: String
    Description: Nombre de dominio para el certificado SSL (por ejemplo, tusitio.com)

  HostedZoneId:
    Type: String
    Description: ID de la zona hospedada en Route 53 (por ejemplo Z123456ABCDEFG)

Resources:
  SSLCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref DomainName
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !Ref DomainName
          HostedZoneId: !Ref HostedZoneId
      Tags:
        - Key: Name
          Value: !Sub "${DomainName}-Cert"

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: index.html
        Aliases:
          - !Ref DomainName
        ViewerCertificate:
          AcmCertificateArn: !Ref SSLCertificate
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021
        Origins:
          - Id: S3RedirectOrigin
            DomainName: !ImportValue POC-S3RedirecttoHost-S3-Redirect-URL
            CustomOriginConfig:
              OriginProtocolPolicy: http-only
              HTTPPort: 80
              OriginSSLProtocols: [TLSv1.2]
          - Id: EC2Origin
            DomainName: !ImportValue POC-S3RedirecttoHost-EC2-DNS
            CustomOriginConfig:
              OriginProtocolPolicy: http-only
              HTTPPort: 80
              OriginSSLProtocols: [TLSv1.2]
        DefaultCacheBehavior:
          TargetOriginId: EC2Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods: [GET, HEAD]
          CachedMethods: [GET, HEAD]
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
        CacheBehaviors:
          - PathPattern: /About.html
            TargetOriginId: S3RedirectOrigin
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods: [GET, HEAD]
            CachedMethods: [GET, HEAD]
            ForwardedValues:
              QueryString: false
              Cookies:
                Forward: none

          - PathPattern: /contact.html
            TargetOriginId: S3RedirectOrigin
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods: [GET, HEAD]
            CachedMethods: [GET, HEAD]
            ForwardedValues:
              QueryString: false
              Cookies:
                Forward: none

          - PathPattern: /empresa/index.html
            TargetOriginId: S3RedirectOrigin
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods: [GET, HEAD]
            CachedMethods: [GET, HEAD]
            ForwardedValues:
              QueryString: false
              Cookies:
                Forward: none

  Route53Record:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref DomainName
      Type: A
      AliasTarget:
        DNSName: !GetAtt CloudFrontDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2  # ID de CloudFront
